### ISSUE TITLE
Maybe wrong check

### ISSUE THREAD

**Issue by zAlweNy26** [micromark/micromark-extension-gfm-tagfilter#1]
### Initial checklist

- [X] I read the [support docs](https://github.com/micromark/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/micromark/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/micromark/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amicromark&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

micromark-extension-gfm@3.0.0

### Steps to reproduce

1. set `allowDangerousHtml` to `true` in micromark.
2. parse some content with an `iframe` in it.
3. see the actual result, the `iframe` tag being shown as raw text.

Using Node.js 20

### Expected behavior

I would expect the `iframe` to be rendered correctly.
I think the check at
https://github.com/micromark/micromark-extension-gfm-tagfilter/blob/4772ae620b521c834bf01df676ebfed68622a2f8/lib/index.js#L44
is wrong, it should have a `!` before.

### Actual behavior

Trying to parse content with an `iframe` and `allowDangerousHtml` set to `true`, the extension continues to escape the tag, causing the iframe tag being shown as raw text.

### Runtime

Other (please specify in steps to reproduce)

### Package manager

pnpm

### OS

Linux

### Build and bundle tools

Vite

**Comment by wooorm** [comment]
Hi!

> see the actual result, the iframe tag being shown as raw text.

Which is what this project does: <iframe>

---

You don‘t want this project, see the readme: https://github.com/micromark/micromark-extension-gfm-tagfilter#what-is-this

**Comment by zAlweNy26** [comment]
@wooorm Hi, thanks for the quick response, I think I didn't understand correctly the readme. I just want to bypass the `replace` if I set `allowDangerousHtml` to `true` in micromark. Can you explain me what am I missing? Sorry for bothering.

**Comment by wooorm** [comment]
You can omit this package. The only thing this package does is that replace. So if you don't need to replace, you can omit it, you don't need the code for it

**Comment by zAlweNy26** [comment]
Yeah I understand that, but `micromark-extension-gfm` is using this package and not giving me an option to disable it

**Comment by wooorm** [comment]
Indeed. `micromark-extension-gfm` does not give an option, because it is a tiny wrapper around several things. I don’t think it’s a good idea to include code that you do not use. Sometimes people don’t want tables. Sometimes they don’t want strikethrough. In such cases, you can pick and choose which of the extension you want. If you don’t want this extension, that’s fine! https://github.com/micromark/micromark-extension-gfm#when-to-use-this
